set -x
set -o noglob
ENGINE=${1:-vllm}
PROJ_ROOT=/fs-computility/mllm1/fangxinyu/plot2code/verl
PROJECT_PACK_PATH=/fs-computility/mllm1/fangxinyu/plot2code/verl/verl/utils/reward_score/chart2code
PROJECT_STORE_PATH=/fs-computility/mllm1/fangxinyu/plot2code/verl/outputs/verl_generated_plot_in_reward
# If you are using vllm<=0.6.3, you might need to set the following environment variable to avoid bugs:
# export VLLM_ATTENTION_BACKEND=XFORMERS

# export TRANSFORMERS_OFFLINE=1
# export HF_HUB_OFFLINE=1
# export RAY_memory_usage_threshold=0.98

python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    data.train_files=$HOME/data/chart2code/train_no_data_True_rollout10k.parquet \
    data.val_files=$HOME/data/chart2code/test_no_data_True_rollout10k.parquet \
    data.train_batch_size=64 \
    data.max_prompt_length=4608 \
    data.max_response_length=4608 \
    data.filter_overlong_prompts=True \
    data.truncation='error' \
    data.image_key=images \
    actor_rollout_ref.model.path=/fs-computility/mllm1/shared/fangxinyu-aliyun/plot2code/LLaMA-Factory/saves/qwen2_5vl-7b/full/sft-160k-onlySingleType-dataProvided/checkpoint-21228 \
    actor_rollout_ref.model.trust_remote_code=True \
    actor_rollout_ref.actor.optim.lr=2e-6 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_epochs=6 \
    actor_rollout_ref.actor.ppo_mini_batch_size=16 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=1 \
    +actor_rollout_ref.critic.ppo_micro_batch_size_per_gpu=1 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.005 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.entropy_coeff=0.01 \
    actor_rollout_ref.actor.clip_ratio=0.15 \
    +actor_rollout_ref.actor.kl_beta_update.target_kl=0.1 \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=16 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.name=$ENGINE \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.65 \
    actor_rollout_ref.rollout.enable_chunked_prefill=False \
    actor_rollout_ref.rollout.enforce_eager=False \
    actor_rollout_ref.rollout.free_cache_engine=False \
    actor_rollout_ref.rollout.n=8 \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=16 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    +actor_rollout_ref.critic.optim.lr=4e-6 \
    +actor_rollout_ref.critic.loss_coef=1.0 \
    algorithm.use_kl_in_reward=False \
    +trainer.lr_scheduler=cosine \
    +trainer.num_warmup_steps=100 \
    trainer.critic_warmup=0 \
    trainer.logger="['console','wandb']" \
    trainer.project_name='verl_qwen2_5_vl_7b_chart2code_rollout10k' \
    trainer.experiment_name='verl_qwen2_5_vl_7b_chart2code_rollout10k_no_data' \
    trainer.n_gpus_per_node=8 \
    trainer.val_before_train=False \
    trainer.nnodes=1 \
    trainer.save_freq=10 \
    trainer.test_freq=10 \
    trainer.resume_mode='auto' \
    trainer.total_epochs=10 $@